/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaguesIndexRouteImport } from './routes/_authenticated/leagues/index'
import { Route as PublicInviteCodeRouteImport } from './routes/_public/invite.$code'
import { Route as AuthenticatedLeaguesNewRouteImport } from './routes/_authenticated/leagues/new'
import { Route as AuthenticatedLeaguesMyRouteImport } from './routes/_authenticated/leagues/my'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaguesIndexRoute =
  AuthenticatedLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicInviteCodeRoute = PublicInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedLeaguesNewRoute = AuthenticatedLeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaguesMyRoute = AuthenticatedLeaguesMyRouteImport.update({
  id: '/leagues/my',
  path: '/leagues/my',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/leagues/my': typeof AuthenticatedLeaguesMyRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/invite/$code': typeof PublicInviteCodeRoute
  '/leagues/': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/leagues/my': typeof AuthenticatedLeaguesMyRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/invite/$code': typeof PublicInviteCodeRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/leagues/my': typeof AuthenticatedLeaguesMyRoute
  '/_authenticated/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/_public/invite/$code': typeof PublicInviteCodeRoute
  '/_authenticated/leagues/': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/leagues/my'
    | '/leagues/new'
    | '/invite/$code'
    | '/leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/leagues/my'
    | '/leagues/new'
    | '/invite/$code'
    | '/leagues'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_public/'
    | '/_authenticated/leagues/my'
    | '/_authenticated/leagues/new'
    | '/_public/invite/$code'
    | '/_authenticated/leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/': {
      id: '/_authenticated/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthenticatedLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/invite/$code': {
      id: '/_public/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof PublicInviteCodeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/leagues/new': {
      id: '/_authenticated/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof AuthenticatedLeaguesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/my': {
      id: '/_authenticated/leagues/my'
      path: '/leagues/my'
      fullPath: '/leagues/my'
      preLoaderRoute: typeof AuthenticatedLeaguesMyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLeaguesMyRoute: typeof AuthenticatedLeaguesMyRoute
  AuthenticatedLeaguesNewRoute: typeof AuthenticatedLeaguesNewRoute
  AuthenticatedLeaguesIndexRoute: typeof AuthenticatedLeaguesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLeaguesMyRoute: AuthenticatedLeaguesMyRoute,
  AuthenticatedLeaguesNewRoute: AuthenticatedLeaguesNewRoute,
  AuthenticatedLeaguesIndexRoute: AuthenticatedLeaguesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInviteCodeRoute: typeof PublicInviteCodeRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInviteCodeRoute: PublicInviteCodeRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
